server:
  port: 8185
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'
    service-id: elastic-query-service
    instances:
      - id: elastic-query-service-1
        host: localhost
        port: 8183
      - id: elastic-query-service-1
        host: localhost
        port: 8186
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client-2'
            client-secret: '{cipher}90e935901c4b17fa000fb7830ece102dc10357d04af97a8c95fe8e9ded65a795c2c3371c8a54f3e6cf23b1bfcfb34b8243096c65721c263d2852ab5ffe8dc881'
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9091/auth/realms/microservices-realm

security:
  logout-success-url: http://localhost:8185/elastic-query-web-client
  default-client-registration-id: keycloak

user-config:
  username: test
  password: '{cipher}afb1592ac57f48d0ef2b6dcf403ccf20aed015bf171470bf78307fe46826e981b0ff2d0ec982ecef34425bc573ab0c7d'
  roles: USER