server:
  port: 8181

twitter-to-kafka-service:
  twitter-keywords:
    - Java
    - Microservices
    - Kafka
    - Elasticsearch
  welcome-message: Hello microservices!
  enable-mock-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 10000
  enable-v2-tweets: true
  twitter-v2-base-url: https://api.twitter.com/2/tweets/search/stream?tweet.fields=created_at&expansions=author_id
  twitter-v2-rules-base-url: https://api.twitter.com/2/tweets/search/stream/rules
  twitter-v2-bearer-token: AAAAAAAAAAAAAAAAAAAAAJ%2FHaQEAAAAAILSXAoQNYnHLmdWq%2FQptGagtrcc%3DPC3qJnDd1OHZRy5qUFTOMPIZaLZVrfp0rWvvlX4Nq4I0J3WcVO

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

#Change these properties if adding the 3rd kafka partition
#bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
 # num-of-partitions: 2
 # replication-factor: 2
kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
    - twitter-analytics-topic
  num-of-partitions: 3
  replication-factor: 3

#Properties comments
#  compression-type: snappy #arranges compression ratio for higher compress/decompress speed. Faster Google library
#  acks: all #all:wait ack from all replicas. 1:wait ack from broker that get requests from producer. 0:dont wait ack
#  batch-size: 16384 #current default value
#  batch-size-boost-factor: 100 #for tuning
#  linger-ms: 5 #delay in producer client to send messages to kafka

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.LongSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5