server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'

spring:
  thymeleaf:
    cache: false

user-config:
  username: test
  password: '{cipher}afb1592ac57f48d0ef2b6dcf403ccf20aed015bf171470bf78307fe46826e981b0ff2d0ec982ecef34425bc573ab0c7d'
  roles: USER