server:
  port: 8182

#Change these properties if adding the 3rd kafka partition
#bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
#concurrency-level: 3

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic

#consumer-group-id= sets a unique id for a consumer to allow using offsets
#auto-offset-reset: earliest = start reading from the beginning of the partition
#batch-listener: true = consume in batches
#auto-startup: false = start reading from topic after checking is there
#concurrency-level: 3 = should be equals to the number of partitions. Ex: 1 topic, 4 partitions = 4
#session-timeout-ms = time broker has to get a heartbeat from consumer
#heartbeat-interval-ms = interval consumer sends heartbeat. Recommended value is 1/3 of session-timeout-ms to give opportunity
#max-poll-interval-ms = If consumer doesnt call poll() before expiration of this timeout, then the consumer is considered failed and the consumer-group will reassign partition
#max-partition-fetch-bytes-default = max bytes fetched in each poll
#poll-timeout-ms = time to wait to retrieve a record. To low cause cpu stall, cpu doesnt progress
kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  consumer-group-id: twitter-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: false
  concurrency-level: 2
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 500
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000

elastic-config:
  index-name: twitter-index
  connection-url: http://localhost:9200
  connect-timeout-ms: 5000
  socket-timeout-ms: 30000
