server:
  port: 8184
  servlet:
    context-path: /elastic-query-web-client

elastic-query-web-client:
  webclient:
    connect-timeout-ms: 10000
    read-timeout-ms: 10000
    write-timeout-ms: 10000
    max-in-memory-size: 10485760 # 10MB
    content-type: 'application/vnd.api.v1+json'
    accept-type: 'application/vnd.api.v1+json'
    base-url: 'http://elastic-query-service/elastic-query-service/documents'
  query-by-text:
    method: POST
    uri: "/get-document-by-text"
    accept: ${elastic-query-web-client.webclient.accept-type}

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: 'elastic-query-web-client'
            client-secret: '{cipher}9301919128124bda4ac2b480b970a6f6c7bdc660d2052d967b78c34473c25fc3697bc34065c7df4fb1d591ef6eeb514682c9959a81c0926b0146f5be1b360635'
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope: openid
        provider:
          keycloak:
            issuerUri: http://localhost:9091/auth/realms/microservices-realm

security:
  logout-success-url: http://localhost:8184/elastic-query-web-client
  default-client-registration-id: keycloak

user-config:
  username: test
  password: '{cipher}afb1592ac57f48d0ef2b6dcf403ccf20aed015bf171470bf78307fe46826e981b0ff2d0ec982ecef34425bc573ab0c7d'
  roles: USER